export * from './comment.interface';
export * from './common.event.interface';
export * from './friend.answer.interface';
export * from './game.banner.interface';
export * from './game.end.interface';
export * from './game.winners.interface';
export * from './get.start.interface';
export * from './question.end.interface';
export * from './question.start.interface';
